---

- hosts: ring
  any_errors_fatal: yes
  become: yes
  
  tasks: 

  
    - name: test connection
      ansible.builtin.ping:


    - name: Stop firewalld
      ansible.builtin.systemd:
          name: firewalld.service
          state: stopped


    - name: Disable service firewalld
      ansible.builtin.systemd:
        name: firewalld
        enabled: no

    
    - name: Disable SELinux
      ansible.posix.selinux:
          state: disabled


    - name: Add DNS to /etc/resolv.conf, without passing regexp
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: nameserver 192.168.1.107
        create: yes

    #due to installs failing if this dir did not already exist, not sure why but making it makes the install work
    - name: create /etc/scality directory unless present
      file:
        path: /etc/scality
        state: directory
        owner: root
        group: root
        mode: 0775

    #same as the dir, an empty file is ok, makes the install work
    - name: create /etc/scality/backup.conf unless present
      blockinfile:
        path: /etc/scality/backup.conf
        block: |
        create: true
        

    #need to add sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/CentOS-Base.repo to ensure yum can install vim/tmux
    - name: Install the latest version of vim
      ansible.builtin.yum:
        name: vim
        state: latest


    - name: Install the latest version of tmux
      ansible.builtin.yum:
        name: tmux
        state: latest


#scal-data* servers only
- hosts: ringdata 
  any_errors_fatal: yes
  become: yes

  tasks:

    #add fix for vmware virtual drives to ensure they show up as ssd or hdd
    - name: Add SSD rotation fix for vmware
      ansible.builtin.lineinfile:
        path: /etc/udev/rules.d/60-ssd-scheduler.rules
        line: ACTION=="add|change", KERNEL=="sd[j-k]", ATTR{queue/rotational}="0", ATTR{queue/scheduler}="deadline"
        create: yes

#scal-conn* servers only
#- hosts: ringconn
#  any_errors_fatal: yes
#  become: yes
#
#  tasks:
#
#    #add fix for vmware virtual drives to ensure they show up as ssd
#    - name: Add SSD rotation fix for vmware
#      ansible.builtin.lineinfile:
#        path: /etc/udev/rules.d/60-ssd-scheduler.rules
#        line: ACTION=="add|change", KERNEL=="sdb", ATTR{queue/rotational}="0", ATTR{queue/scheduler}="deadline"
#        create: yes
#
#    - name: Add HDD rotation fix for vmware
#      ansible.builtin.lineinfile:
#        path: /etc/udev/rules.d/60-ssd-scheduler.rules
#        line: ACTION=="add|change", KERNEL=="sda", ATTR{queue/rotational}="1", ATTR{queue/scheduler}="deadline"
#        create: yes
