#!/bin/bash
#setup ssh on new lab for ansbile playbook and future work

for i in {0..6};do ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.5${i};done
#for i in {1..3};do ssh-copy-id -i ~/.ssh/id_rsa.pub root@192.168.1.6${i};done

#copy over saved .ssh dir from previous install so all keys remain the same
#for i in {0..3};do scp -r 192.168.1.5${i}/.ssh root@192.168.1.5${i}:/root/ ;done
