---

- hosts: ring
  any_errors_fatal: yes
  become: yes
  
  tasks: 

  
    - name: test connection
      ansible.builtin.ping:





    - name: create /etc/scality directory if it does not exist
      file:
        path: /etc/scality
        state: directory
        owner: root
        group: root
        mode: 0775


    - name: Update/create block if needed. Create file if not exists
      blockinfile:
        path: /tmp/backup.conf
        block: |
        create: true
