#!/bin/bash
#wipe lab drives for fresh install

for host in {1..6}
do 
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "systemctl stop scality-*.mount"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "for disk in $(lsblk -o MOUNTPOINT |grep scality);do umount -f ${disk};done"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdb"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdc"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdd"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sde"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdf"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdg"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdh"
    echo "192.168.1.5${host}";ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdi"
#    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdj"
#    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdk"
#    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdl"
#    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdm"

done
echo $(date +"%Y-%m-%d_%H.%M")

#sleep 1
#for host in {1..3}
#do
#    ssh root@192.168.1.6${host} "for disk in $(lsblk -o MOUNTPOINT |grep scality);do umount -f ${disk};done"
#    ssh root@192.168.1.6${host} "/usr/sbin/wipefs -a -f /dev/sdb"
#done
