#!/bin/bash
#wipe lab drives for fresh install

for host in {1..6}
do 
    ssh root@192.168.1.5${host} "systemctl stop scality-*.mount"
    ssh root@192.168.1.5${host} "for disk in $(lsblk -o MOUNTPOINT |grep scality);do umount -f ${disk};done"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdb"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdc"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdd"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sde"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdf"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdg"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdh"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdi"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdj"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdk"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdl"
    ssh root@192.168.1.5${host} "/usr/sbin/wipefs -a -f /dev/sdm"


done
#sleep 1
#for host in {1..3}
#do
#    ssh root@192.168.1.6${host} "for disk in $(lsblk -o MOUNTPOINT |grep scality);do umount -f ${disk};done"
#    ssh root@192.168.1.6${host} "/usr/sbin/wipefs -a -f /dev/sdb"
#done
